### ISSUE TITLE
Vulkan init error and crashed when minimize or resized on windows 10

### ISSUE THREAD

**Issue by happydpc** [aclysma/engine_prototype#27]
Here's the info, with GTX 1070s

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreateInstanceError(InstanceError(VkError(ERROR_LAYER_NOT_PRESENT)))', engine\src\init.rs:112:53
stack backtrace:
[2020-08-07T13:05:14.598022500Z DEBUG engine::assets::gltf::importer] Importing material instance uuid AssetUuid(c6a2bd92-a3ff-41be-9d17-1a83b10bf049)
[2020-08-07T13:05:14.598051000Z DEBUG engine::assets::gltf::importer] Importing material instance uuid AssetUuid(6476ac04-b67f-4579-9ae8-879e1040e302)
[2020-08-07T13:05:14.598071100Z DEBUG engine::assets::gltf::importer] Importing material instance uuid AssetUuid(5669f73a-6178-4d2f-a22d-6b1b8d25f9ec)

**Comment by aclysma** [comment]
This error almost certainly means the vulkan SDK is not installed. It is required to run with validation enabled. Another option is to modify the code to not use validation.

**Comment by happydpc** [comment]
I am using vulkan 1.2.135.0. Running wgpu-rs examples are ok. Seems that the validation needs to turn off.

**Comment by happydpc** [comment]
But now, I check the init logic, the debug layer is off

 let mut context = VkContextBuilder::new()
        .use_vulkan_debug_layer(false)
        .msaa_level_priority(vec![msaa_level])
        .prefer_mailbox_present_mode();

**Comment by happydpc** [comment]
Turn off validation, the demo runs ok, But when minimize the application, it crashed.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_OUT_OF_DATE_KHR', engine\src\lib.rs:216:18

**Comment by aclysma** [comment]
Ah yeah, that’s a known issue. It was introduced when I switched to pipelining rendering in a different thread. This project is not ready for other people to use, I only made it public because it has good examples of using atelier-assets and legion. It is even more prototype-y than renderer_prototype :D
